kind: PersistentVolume
apiVersion: v1
metadata:
  name: mydb
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "mydb-disk"
    fsType: "ext4"
